# This is a variable learning workflow
name: Variable Learning Workflow

env:
  cloud: google-cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      greetings: Good morning
    steps:
      - uses: actions/checkout@v6

      - name: Run a one-line script
        run: |
            echo "Hello, $greetings its me $name is using $cloud ${{vars.ProjectID}} with Secret Key ${{secrets.Key}}"
             echo "repository name: ${{github.repository}}"
             echo "Triggered By: ${{github.triggering_actor}}"
        env:
          name: Vishnu K Kumar

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
